# Generated by Django 5.1.3 on 2024-12-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='photo',
            new_name='image',
        ),
    ]
