# Generated by Django 5.1.3 on 2024-12-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor_name', models.CharField(max_length=255, verbose_name='Имя предка')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Степень родства')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='dogs.dog')),
            ],
        ),
    ]
