# Generated by Django 5.1.4 on 2024-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_pedigree'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
